[package]
name = "michelaguilera/infiniteobbysystems"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.3"
suphisdatastoremodule = "skylord-103/suphisdatastoremodule@1.0.0"